- name: Harden the local Kali machine
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: hardening
      tags: hardening

- name: Deploy Nginx web server
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: webserver
      tags: webserver